### ISSUE TITLE
missing less subdirectory

### ISSUE THREAD

**Issue by kev009** [webjars/bootstrap-datepicker#14]
1.4.0 looks to be missing a number of files, but the missing less subdir is burning me trying to upgrade from 1.3.1.

**Comment by jamesward** [comment]
We use the upstream dist download for the WebJar: https://github.com/eternicode/bootstrap-datepicker/releases

That doesn't contain the `less` sources.  So that is why they aren't included in the WebJar.  Maybe a Bower WebJar would be more appropriate?
